version: 2.1

jobs:
  lint:
    docker:
      - image: circleci/python:3.8-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - mongo-types-v1-{{ checksum "poetry.lock" }}
      - run:
          name: Install python dependencies
          command: |
            # Use our new PATH so we can call poetry from bash
            echo 'export PATH="$PATH":"$HOME"/.local/bin' >> $BASH_ENV
            source $BASH_ENV
            sudo python -m pip install -U pip
            sudo python -m pip install -U poetry
            poetry install
      - run:
          name: Install pyright
          command: |
            # Pyright is installed at first call (using pyright wrapper and nodeenv)
            poetry run pyright --version
      - save_cache:
          paths:
            - ./.mypy_cache
            - .venv
            - /root/.cache/
          key: mongo-types-v1-{{ checksum "poetry.lock" }}
      - run:
          name: lint
          command: ./s/lint

workflows:
  version: 2
  test:
    jobs:
      - lint
